// Code generated by goyacc -l -o promql/parser/generated_parser.y.go promql/parser/generated_parser.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"math"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/model/histogram"
	"github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/model/value"
	"github.com/prometheus/prometheus/promql/parser/posrange"

	"github.com/prometheus/common/model"
)

type yySymType struct {
	yys         int
	node        Node
	item        Item
	matchers    []*labels.Matcher
	matcher     *labels.Matcher
	label       labels.Label
	labels      labels.Labels
	lblList     []labels.Label
	strings     []string
	series      []SequenceValue
	histogram   *histogram.FloatHistogram
	descriptors map[string]interface{}
	bucket_set  []float64
	int         int64
	uint        uint64
	float       float64
	on_match    *onMatchClause
	label_map   LabelMapping
}

const EQL = 57346
const BLANK = 57347
const COLON = 57348
const COMMA = 57349
const COMMENT = 57350
const DURATION = 57351
const EOF = 57352
const ERROR = 57353
const IDENTIFIER = 57354
const LEFT_BRACE = 57355
const LEFT_BRACKET = 57356
const LEFT_PAREN = 57357
const OPEN_HIST = 57358
const CLOSE_HIST = 57359
const METRIC_IDENTIFIER = 57360
const NUMBER = 57361
const RIGHT_BRACE = 57362
const RIGHT_BRACKET = 57363
const RIGHT_PAREN = 57364
const SEMICOLON = 57365
const SPACE = 57366
const STRING = 57367
const TIMES = 57368
const histogramDescStart = 57369
const SUM_DESC = 57370
const COUNT_DESC = 57371
const SCHEMA_DESC = 57372
const OFFSET_DESC = 57373
const NEGATIVE_OFFSET_DESC = 57374
const BUCKETS_DESC = 57375
const NEGATIVE_BUCKETS_DESC = 57376
const ZERO_BUCKET_DESC = 57377
const ZERO_BUCKET_WIDTH_DESC = 57378
const CUSTOM_VALUES_DESC = 57379
const COUNTER_RESET_HINT_DESC = 57380
const histogramDescEnd = 57381
const operatorsStart = 57382
const ADD = 57383
const DIV = 57384
const EQLC = 57385
const EQL_REGEX = 57386
const GTE = 57387
const GTR = 57388
const TRIM_UPPER = 57389
const TRIM_LOWER = 57390
const LAND = 57391
const LOR = 57392
const LSS = 57393
const LTE = 57394
const LUNLESS = 57395
const MOD = 57396
const MUL = 57397
const NEQ = 57398
const NEQ_REGEX = 57399
const POW = 57400
const SUB = 57401
const AT = 57402
const ATAN2 = 57403
const operatorsEnd = 57404
const aggregatorsStart = 57405
const AVG = 57406
const BOTTOMK = 57407
const COUNT = 57408
const COUNT_VALUES = 57409
const GROUP = 57410
const MAX = 57411
const MIN = 57412
const QUANTILE = 57413
const STDDEV = 57414
const STDVAR = 57415
const SUM = 57416
const TOPK = 57417
const LIMITK = 57418
const LIMIT_RATIO = 57419
const aggregatorsEnd = 57420
const keywordsStart = 57421
const BOOL = 57422
const BY = 57423
const GROUP_LEFT = 57424
const GROUP_RIGHT = 57425
const FILL = 57426
const FILL_LEFT = 57427
const FILL_RIGHT = 57428
const IGNORING = 57429
const OFFSET = 57430
const SMOOTHED = 57431
const ANCHORED = 57432
const ON = 57433
const WITHOUT = 57434
const keywordsEnd = 57435
const preprocessorStart = 57436
const START = 57437
const END = 57438
const STEP = 57439
const RANGE = 57440
const MAX_OF = 57441
const MIN_OF = 57442
const preprocessorEnd = 57443
const counterResetHintsStart = 57444
const UNKNOWN_COUNTER_RESET = 57445
const COUNTER_RESET = 57446
const NOT_COUNTER_RESET = 57447
const GAUGE_TYPE = 57448
const counterResetHintsEnd = 57449
const startSymbolsStart = 57450
const START_METRIC = 57451
const START_SERIES_DESCRIPTION = 57452
const START_EXPRESSION = 57453
const START_METRIC_SELECTOR = 57454
const startSymbolsEnd = 57455

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EQL",
	"BLANK",
	"COLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"OPEN_HIST",
	"CLOSE_HIST",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"histogramDescStart",
	"SUM_DESC",
	"COUNT_DESC",
	"SCHEMA_DESC",
	"OFFSET_DESC",
	"NEGATIVE_OFFSET_DESC",
	"BUCKETS_DESC",
	"NEGATIVE_BUCKETS_DESC",
	"ZERO_BUCKET_DESC",
	"ZERO_BUCKET_WIDTH_DESC",
	"CUSTOM_VALUES_DESC",
	"COUNTER_RESET_HINT_DESC",
	"histogramDescEnd",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQLC",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"TRIM_UPPER",
	"TRIM_LOWER",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"POW",
	"SUB",
	"AT",
	"ATAN2",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"GROUP",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"LIMITK",
	"LIMIT_RATIO",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"FILL",
	"FILL_LEFT",
	"FILL_RIGHT",
	"IGNORING",
	"OFFSET",
	"SMOOTHED",
	"ANCHORED",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"preprocessorStart",
	"START",
	"END",
	"STEP",
	"RANGE",
	"MAX_OF",
	"MIN_OF",
	"preprocessorEnd",
	"counterResetHintsStart",
	"UNKNOWN_COUNTER_RESET",
	"COUNTER_RESET",
	"NOT_COUNTER_RESET",
	"GAUGE_TYPE",
	"counterResetHintsEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 46,
	1, 178,
	10, 178,
	24, 178,
	-2, 0,
	-1, 78,
	2, 221,
	15, 221,
	81, 221,
	92, 221,
	-2, 130,
	-1, 79,
	2, 222,
	15, 222,
	81, 222,
	92, 222,
	-2, 131,
	-1, 80,
	2, 223,
	15, 223,
	81, 223,
	92, 223,
	-2, 133,
	-1, 81,
	2, 224,
	15, 224,
	81, 224,
	92, 224,
	-2, 134,
	-1, 82,
	2, 225,
	15, 225,
	81, 225,
	92, 225,
	-2, 138,
	-1, 83,
	2, 226,
	15, 226,
	81, 226,
	92, 226,
	-2, 143,
	-1, 84,
	2, 227,
	15, 227,
	81, 227,
	92, 227,
	-2, 145,
	-1, 85,
	2, 228,
	15, 228,
	81, 228,
	92, 228,
	-2, 147,
	-1, 86,
	2, 229,
	15, 229,
	81, 229,
	92, 229,
	-2, 148,
	-1, 87,
	2, 230,
	15, 230,
	81, 230,
	92, 230,
	-2, 149,
	-1, 88,
	2, 231,
	15, 231,
	81, 231,
	92, 231,
	-2, 150,
	-1, 89,
	2, 232,
	15, 232,
	81, 232,
	92, 232,
	-2, 151,
	-1, 90,
	2, 233,
	15, 233,
	81, 233,
	92, 233,
	-2, 155,
	-1, 91,
	2, 234,
	15, 234,
	81, 234,
	92, 234,
	-2, 156,
	-1, 92,
	15, 102,
	-2, 153,
	-1, 93,
	15, 103,
	-2, 154,
	-1, 94,
	15, 304,
	-2, 161,
	-1, 95,
	15, 305,
	-2, 162,
	-1, 156,
	41, 307,
	42, 307,
	54, 307,
	55, 307,
	59, 307,
	-2, 22,
	-1, 274,
	9, 292,
	12, 292,
	13, 292,
	18, 292,
	19, 292,
	25, 292,
	41, 292,
	49, 292,
	50, 292,
	53, 292,
	59, 292,
	64, 292,
	65, 292,
	66, 292,
	67, 292,
	68, 292,
	69, 292,
	70, 292,
	71, 292,
	72, 292,
	73, 292,
	74, 292,
	75, 292,
	76, 292,
	77, 292,
	81, 292,
	84, 292,
	85, 292,
	86, 292,
	88, 292,
	89, 292,
	90, 292,
	92, 292,
	95, 292,
	96, 292,
	97, 292,
	98, 292,
	99, 292,
	100, 292,
	-2, 0,
	-1, 275,
	9, 292,
	12, 292,
	13, 292,
	18, 292,
	19, 292,
	25, 292,
	41, 292,
	49, 292,
	50, 292,
	53, 292,
	59, 292,
	64, 292,
	65, 292,
	66, 292,
	67, 292,
	68, 292,
	69, 292,
	70, 292,
	71, 292,
	72, 292,
	73, 292,
	74, 292,
	75, 292,
	76, 292,
	77, 292,
	81, 292,
	84, 292,
	85, 292,
	86, 292,
	88, 292,
	89, 292,
	90, 292,
	92, 292,
	95, 292,
	96, 292,
	97, 292,
	98, 292,
	99, 292,
	100, 292,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 1808

var yyAct = [...]int16{
	63, 205, 444, 445, 463, 386, 461, 208, 468, 374,
	263, 216, 394, 53, 395, 209, 105, 160, 103, 247,
	440, 176, 66, 272, 407, 139, 74, 273, 140, 217,
	132, 71, 475, 476, 477, 478, 71, 204, 69, 441,
	142, 70, 204, 406, 274, 275, 70, 269, 270, 271,
	207, 143, 76, 138, 368, 458, 132, 213, 112, 417,
	457, 419, 365, 96, 417, 170, 141, 212, 96, 369,
	123, 124, 136, 154, 126, 156, 131, 111, 366, 144,
	6, 97, 494, 479, 137, 135, 97, 370, 138, 214,
	502, 213, 447, 214, 145, 146, 147, 149, 151, 462,
	126, 212, 131, 504, 128, 130, 129, 215, 446, 501,
	426, 215, 500, 409, 408, 162, 404, 364, 402, 221,
	222, 202, 203, 214, 221, 222, 202, 203, 157, 201,
	128, 130, 129, 218, 224, 225, 226, 227, 228, 229,
	363, 215, 196, 210, 211, 142, 219, 219, 219, 219,
	219, 219, 219, 241, 206, 197, 143, 232, 235, 220,
	220, 220, 220, 220, 220, 220, 231, 200, 230, 401,
	213, 223, 223, 223, 223, 223, 223, 223, 265, 267,
	212, 487, 253, 163, 255, 362, 266, 2, 3, 4,
	5, 387, 425, 161, 71, 357, 195, 399, 298, 398,
	204, 359, 214, 71, 70, 302, 107, 424, 361, 204,
	356, 293, 469, 70, 423, 133, 136, 71, 219, 503,
	215, 298, 304, 305, 220, 259, 96, 70, 137, 135,
	71, 220, 138, 134, 219, 96, 296, 314, 133, 136,
	70, 485, 257, 223, 97, 397, 484, 220, 258, 96,
	452, 137, 135, 97, 71, 138, 134, 133, 136, 223,
	297, 483, 162, 360, 70, 256, 311, 97, 310, 451,
	137, 135, 309, 303, 138, 134, 388, 389, 367, 213,
	301, 499, 221, 222, 202, 203, 96, 390, 396, 212,
	455, 198, 199, 202, 203, 300, 299, 144, 400, 152,
	133, 136, 403, 234, 97, 150, 148, 98, 218, 133,
	136, 219, 410, 137, 135, 219, 233, 138, 134, 405,
	132, 219, 137, 135, 220, 219, 138, 134, 220, 44,
	7, 437, 436, 435, 220, 434, 223, 433, 220, 432,
	223, 358, 294, 295, 202, 203, 223, 110, 112, 413,
	223, 431, 238, 10, 412, 393, 450, 48, 249, 415,
	123, 124, 430, 100, 126, 127, 131, 111, 392, 411,
	416, 418, 219, 420, 429, 133, 136, 428, 427, 486,
	421, 422, 168, 308, 167, 220, 449, 307, 137, 135,
	133, 136, 138, 134, 128, 130, 129, 223, 251, 169,
	448, 438, 306, 137, 135, 133, 136, 138, 134, 61,
	250, 252, 109, 219, 439, 99, 454, 75, 137, 135,
	9, 9, 138, 134, 456, 153, 220, 155, 45, 1,
	464, 465, 466, 460, 194, 171, 243, 77, 223, 467,
	246, 471, 470, 473, 472, 245, 481, 482, 60, 59,
	248, 488, 249, 480, 58, 133, 136, 57, 244, 175,
	106, 166, 489, 490, 219, 56, 165, 491, 137, 135,
	104, 493, 138, 134, 55, 163, 106, 220, 254, 164,
	8, 54, 52, 107, 46, 161, 104, 496, 498, 223,
	497, 173, 251, 159, 102, 236, 51, 174, 107, 107,
	50, 219, 505, 172, 250, 252, 49, 62, 262, 492,
	371, 108, 260, 442, 220, 391, 312, 101, 474, 315,
	64, 158, 0, 0, 268, 0, 223, 0, 0, 0,
	276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
	286, 287, 288, 289, 290, 291, 292, 177, 178, 179,
	180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
	190, 191, 192, 193, 317, 261, 0, 0, 0, 213,
	0, 0, 264, 0, 330, 0, 267, 0, 373, 212,
	336, 0, 0, 0, 495, 372, 0, 316, 0, 376,
	377, 375, 382, 384, 381, 383, 378, 379, 380, 385,
	0, 214, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 332, 333, 0, 0, 334, 0, 0, 0, 215,
	0, 0, 0, 347, 0, 0, 318, 320, 322, 323,
	324, 335, 337, 340, 341, 342, 343, 344, 348, 349,
	0, 0, 319, 321, 325, 326, 327, 328, 329, 331,
	338, 353, 352, 339, 317, 0, 0, 345, 346, 350,
	351, 354, 355, 0, 330, 0, 0, 459, 0, 0,
	336, 0, 0, 0, 453, 0, 0, 316, 376, 377,
	375, 382, 384, 381, 383, 378, 379, 380, 385, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 332, 333, 0, 0, 334, 0, 0, 0, 0,
	414, 0, 0, 347, 0, 0, 318, 320, 322, 323,
	324, 335, 337, 340, 341, 342, 343, 344, 348, 349,
	0, 0, 319, 321, 325, 326, 327, 328, 329, 331,
	338, 353, 352, 339, 317, 0, 0, 345, 346, 350,
	351, 354, 355, 0, 330, 0, 0, 0, 0, 0,
	336, 0, 0, 0, 443, 0, 0, 316, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 332, 333, 0, 0, 334, 0, 0, 0, 0,
	0, 0, 0, 347, 0, 0, 318, 320, 322, 323,
	324, 335, 337, 340, 341, 342, 343, 344, 348, 349,
	0, 0, 319, 321, 325, 326, 327, 328, 329, 331,
	338, 353, 352, 339, 317, 0, 0, 345, 346, 350,
	351, 354, 355, 0, 330, 0, 0, 0, 0, 0,
	336, 0, 0, 0, 313, 0, 0, 316, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 332, 333, 0, 0, 334, 0, 0, 0, 0,
	0, 0, 0, 347, 0, 0, 318, 320, 322, 323,
	324, 335, 337, 340, 341, 342, 343, 344, 348, 349,
	0, 0, 319, 321, 325, 326, 327, 328, 329, 331,
	338, 353, 352, 339, 0, 0, 0, 345, 346, 350,
	351, 354, 355, 71, 0, 0, 65, 98, 0, 72,
	0, 0, 25, 70, 0, 0, 237, 0, 0, 73,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 96, 0, 0, 0, 0,
	0, 0, 0, 21, 22, 0, 0, 23, 0, 0,
	0, 0, 0, 97, 0, 0, 0, 0, 78, 79,
	80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
	90, 91, 0, 0, 0, 13, 0, 0, 16, 17,
	18, 0, 27, 41, 40, 0, 33, 0, 0, 92,
	93, 67, 68, 94, 95, 71, 0, 0, 65, 98,
	0, 72, 0, 0, 25, 70, 0, 0, 240, 0,
	0, 73, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 96, 0, 0,
	0, 0, 0, 0, 0, 21, 22, 0, 0, 23,
	0, 0, 0, 0, 0, 97, 0, 0, 0, 0,
	78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
	88, 89, 90, 91, 0, 0, 0, 13, 0, 0,
	16, 17, 18, 0, 27, 41, 40, 0, 33, 0,
	0, 92, 93, 67, 68, 94, 95, 71, 0, 0,
	65, 98, 0, 72, 0, 0, 25, 70, 0, 0,
	239, 0, 0, 73, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 96,
	0, 0, 0, 0, 0, 0, 0, 21, 22, 0,
	0, 23, 0, 0, 0, 0, 0, 97, 0, 0,
	0, 0, 78, 79, 80, 81, 82, 83, 84, 85,
	86, 87, 88, 89, 90, 91, 0, 0, 0, 13,
	0, 0, 16, 17, 18, 0, 27, 41, 40, 0,
	33, 0, 0, 92, 93, 67, 68, 94, 95, 71,
	47, 0, 65, 98, 0, 72, 0, 0, 25, 70,
	0, 0, 0, 0, 0, 73, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 96, 0, 0, 0, 0, 0, 0, 0, 21,
	22, 0, 0, 23, 0, 0, 0, 0, 0, 97,
	0, 0, 0, 0, 78, 79, 80, 81, 82, 83,
	84, 85, 86, 87, 88, 89, 90, 91, 0, 0,
	0, 13, 0, 0, 16, 17, 18, 0, 27, 41,
	40, 317, 33, 0, 0, 92, 93, 67, 68, 94,
	95, 330, 0, 0, 0, 0, 0, 336, 0, 0,
	0, 0, 0, 0, 316, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 332, 333,
	0, 0, 334, 0, 0, 0, 0, 0, 0, 0,
	347, 0, 0, 318, 320, 322, 323, 324, 335, 337,
	340, 341, 342, 343, 344, 348, 349, 0, 0, 319,
	321, 325, 326, 327, 328, 329, 331, 338, 353, 352,
	339, 0, 0, 0, 345, 346, 350, 351, 354, 355,
	71, 0, 0, 65, 98, 0, 72, 0, 0, 25,
	70, 0, 0, 0, 0, 0, 73, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 96, 0, 0, 0, 0, 0, 0, 0,
	21, 22, 0, 0, 23, 0, 0, 0, 0, 0,
	97, 0, 0, 0, 0, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 87, 88, 89, 90, 91, 0,
	0, 0, 13, 0, 0, 16, 17, 18, 0, 27,
	41, 40, 0, 33, 0, 0, 92, 93, 67, 68,
	94, 95, 20, 98, 0, 0, 0, 0, 25, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 21,
	22, 0, 0, 23, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 11, 12, 14, 15, 19, 24,
	26, 28, 29, 30, 31, 32, 36, 37, 0, 0,
	0, 13, 0, 0, 16, 17, 18, 0, 27, 41,
	40, 0, 33, 0, 0, 34, 35, 38, 39, 42,
	43, 20, 44, 0, 0, 0, 0, 25, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 21, 22,
	0, 0, 23, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 11, 12, 14, 15, 19, 24, 26,
	28, 29, 30, 31, 32, 36, 37, 0, 132, 0,
	13, 0, 0, 16, 17, 18, 242, 27, 41, 40,
	0, 33, 0, 0, 34, 35, 38, 39, 42, 43,
	132, 0, 0, 0, 0, 110, 112, 113, 0, 114,
	115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
	125, 0, 126, 127, 131, 111, 0, 110, 112, 113,
	0, 114, 115, 116, 117, 118, 119, 120, 121, 122,
	123, 124, 125, 0, 126, 127, 131, 111, 0, 0,
	132, 0, 128, 130, 129, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 132, 0, 0, 128, 130, 129, 110, 112, 113,
	0, 114, 115, 116, 117, 118, 0, 120, 121, 122,
	123, 124, 125, 0, 126, 127, 131, 111, 110, 112,
	113, 0, 114, 115, 116, 117, 0, 0, 120, 121,
	0, 123, 124, 125, 0, 126, 127, 131, 111, 0,
	0, 0, 0, 0, 128, 130, 129, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 128, 130, 129,
}

var yyPact = [...]int16{
	78, 320, 1559, 1559, 1200, 1470, -1000, -1000, -1000, 316,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 474, -1000, 410, -1000, 1646, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 216, 64, 282, 282, 291, 290, 284,
	-1000, -1000, 1381, -1000, 1381, 294, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 473, -1000,
	-1000, 459, -1000, -1000, 380, 395, -1000, -1000, 41, -1000,
	-59, -59, -59, -59, -59, -59, -59, -59, -59, -59,
	-59, -59, -59, -59, -59, -59, -59, -59, 194, -1000,
	-1000, 48, 27, 185, 185, 185, 185, 185, 185, 282,
	-41, -1000, 301, 301, 924, -1000, -1000, -1000, 1108, -1000,
	1016, -1000, 924, 1624, 414, 42, -5, -1000, 438, -1000,
	-1000, 448, 354, -1000, -1000, 458, -1000, 240, -1000, 223,
	560, 1381, -1000, -37, -64, -38, -1000, 1381, 1381, 1381,
	1381, 1381, 1381, 1381, 1381, 1381, 1381, 1381, 1381, 1381,
	1381, 1381, 1381, 1381, -1000, -1000, -1000, 245, 281, 280,
	265, 216, -1000, -1000, 185, -1000, 258, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 270, 270, 381, -1000, 216, -1000,
	185, 257, 253, 251, 30, 30, -5, -5, -5, -5,
	-1000, -1000, -1000, 832, -1000, -1000, 188, -1000, 1646, -1000,
	-1000, 334, -1000, -1000, -1000, 181, -1000, 183, -1000, -1000,
	-1000, -1000, -1000, 115, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 36, 52, 28, -1000, -1000, -1000, 561, 16, 176,
	176, 176, 301, 353, 301, 301, 42, 42, 306, 306,
	306, 306, 306, 1717, 1696, 306, 306, 1717, 42, 42,
	306, 42, 16, -1000, 230, 184, 182, 185, -5, 147,
	96, 185, 414, 94, -1000, -1000, -1000, 22, -1000, 92,
	91, 185, 347, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 1381, 185, -1000,
	-1000, -1000, -1000, -1000, -1000, 45, 45, 35, 45, 163,
	163, 190, 93, -1000, -1000, 372, 371, 368, 356, 345,
	333, 331, 329, 327, 326, 325, -1000, 208, -66, -46,
	-1000, -1000, 742, -1000, -1000, -1000, -1000, 86, 70, 185,
	364, -1000, -1000, 349, -1000, 248, -1000, -1000, -1000, -1000,
	334, -1000, 652, -1000, 1646, 268, -1000, -1000, -1000, 45,
	-1000, 34, 29, 650, -1000, -1000, -1000, 40, 161, 161,
	161, 270, 198, 198, 40, 198, 40, -71, 61, 221,
	176, 176, 239, -1000, -1000, 375, -1000, -1000, 174, -1000,
	185, -1000, -1000, -1000, -1000, -1000, -1000, 45, 45, -1000,
	-1000, -1000, 45, -1000, -1000, -1000, -1000, -1000, -1000, 161,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	60, -1000, -1000, -1000, 562, -1000, 1289, 185, 259, -1000,
	-1000, -1000, 88, -1000, -1000, -1000, -1000, -1000, 197, -1000,
	82, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 521, 17, 520, 3, 19, 519, 417, 26, 22,
	16, 518, 38, 353, 480, 517, 18, 516, 14, 12,
	515, 513, 2, 512, 511, 10, 510, 9, 8, 509,
	6, 4, 7, 508, 15, 1, 507, 506, 25, 435,
	503, 500, 497, 352, 496, 495, 28, 491, 5, 52,
	482, 13, 481, 474, 465, 459, 457, 454, 449, 448,
	409, 0, 437, 11, 434, 429, 428,
}

var yyR1 = [...]int8{
	0, 65, 65, 65, 65, 65, 65, 65, 43, 43,
	43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
	43, 43, 43, 37, 37, 37, 37, 38, 38, 41,
	41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
	41, 41, 41, 41, 41, 41, 41, 39, 42, 42,
	55, 55, 47, 47, 47, 47, 40, 40, 40, 40,
	40, 40, 18, 18, 18, 18, 20, 20, 20, 20,
	21, 21, 21, 22, 22, 17, 17, 17, 4, 4,
	4, 48, 48, 44, 44, 44, 44, 44, 46, 46,
	45, 45, 45, 56, 63, 52, 52, 53, 54, 36,
	36, 36, 9, 9, 50, 58, 58, 58, 58, 58,
	58, 59, 60, 60, 60, 49, 49, 49, 1, 1,
	1, 2, 2, 2, 2, 2, 2, 2, 14, 14,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 13, 13, 13, 13, 15, 15, 15,
	16, 16, 16, 16, 16, 16, 16, 66, 24, 24,
	24, 24, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 33, 33, 33, 25, 25, 25, 25, 26, 26,
	26, 27, 27, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 28, 28, 29, 29, 29, 11, 11, 11,
	11, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 8, 8, 5, 5, 5, 5, 51,
	51, 32, 32, 34, 34, 35, 35, 31, 30, 30,
	57, 10, 19, 19, 64, 64, 64, 64, 64, 64,
	64, 64, 64, 64, 12, 12, 61, 61, 61, 61,
	61, 61, 61, 61, 61, 61, 61, 61, 62,
}

var yyR2 = [...]int8{
	0, 2, 2, 2, 2, 2, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 3, 2, 2, 2, 2, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 1, 0, 1,
	3, 3, 1, 1, 3, 3, 1, 3, 3, 3,
	5, 5, 3, 4, 2, 1, 3, 4, 2, 1,
	3, 1, 2, 1, 3, 3, 1, 2, 1, 1,
	1, 3, 4, 2, 2, 2, 2, 2, 3, 2,
	3, 1, 2, 3, 1, 3, 3, 2, 2, 3,
	5, 3, 1, 1, 4, 6, 5, 6, 5, 4,
	3, 2, 2, 1, 1, 3, 4, 2, 3, 1,
	2, 3, 3, 1, 3, 3, 2, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 4, 2, 0, 3, 1, 2,
	3, 3, 1, 3, 3, 2, 1, 2, 0, 3,
	2, 1, 1, 3, 1, 3, 4, 1, 3, 5,
	5, 1, 1, 1, 4, 3, 3, 2, 3, 1,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 4, 3, 3, 1, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 2, 2, 1, 1, 1, 2, 1,
	1, 1, 0, 1, 1, 2, 3, 3, 4, 4,
	6, 7, 4, 1, 1, 1, 1, 2, 3, 3,
	3, 3, 3, 3, 3, 3, 6, 1, 3,
}

var yyChk = [...]int16{
	-1000, -65, 109, 110, 111, 112, 2, 10, -14, -7,
	-13, 64, 65, 81, 66, 67, 84, 85, 86, 68,
	12, 49, 50, 53, 69, 18, 70, 88, 71, 72,
	73, 74, 75, 92, 95, 96, 76, 77, 97, 98,
	90, 89, 99, 100, 13, -66, -14, 10, -43, -37,
	-41, -44, -50, -51, -52, -53, -54, -56, -57, -58,
	-59, -60, -36, -61, -3, 12, -9, 97, 98, -12,
	19, 9, 15, 25, -8, -7, -49, -62, 64, 65,
	66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
	76, 77, 95, 96, 99, 100, 41, 59, 13, -60,
	-13, -15, 20, -16, 12, -10, 2, 25, -24, 2,
	41, 61, 42, 43, 45, 46, 47, 48, 49, 50,
	51, 52, 53, 54, 55, 56, 58, 59, 88, 90,
	89, 60, 14, 41, 59, 55, 42, 54, 58, -38,
	-46, 2, 81, 92, 15, -46, -46, -46, 15, -46,
	15, -46, 15, -43, -61, -43, -61, -49, -1, 20,
	-2, 12, -10, 2, 20, 7, 2, 4, 2, 4,
	24, -39, -40, -47, -42, -55, 80, -39, -39, -39,
	-39, -39, -39, -39, -39, -39, -39, -39, -39, -39,
	-39, -39, -39, -39, -64, 2, -51, -8, 97, 98,
	-12, -61, 99, 100, 15, -35, -9, 2, -32, -34,
	95, 96, 19, 9, 41, 59, -63, 2, -61, -51,
	-8, 97, 98, -12, -61, -61, -61, -61, -61, -61,
	-46, -38, -18, 15, 2, -18, -45, 22, -43, 22,
	22, -61, 22, 22, 20, 7, 2, -5, 2, 4,
	56, 44, 57, -5, 20, -16, 25, 2, 25, 2,
	-23, 5, -33, -25, 12, -32, -34, 16, -43, 84,
	85, 86, 87, 91, 82, 83, -43, -43, -43, -43,
	-43, -43, -43, -43, -43, -43, -43, -43, -43, -43,
	-43, -43, -43, -51, 97, 98, -12, 15, -61, 15,
	15, 15, -61, 15, -32, -32, 21, 6, 2, 15,
	15, 15, -17, 22, -4, -6, 25, 2, 64, 80,
	65, 81, 66, 67, 68, 82, 83, 84, 85, 86,
	12, 87, 49, 50, 53, 69, 18, 70, 88, 91,
	71, 72, 73, 74, 75, 95, 96, 61, 76, 77,
	97, 98, 90, 89, 99, 100, 22, 7, 7, 20,
	-2, 25, 2, 25, 2, 26, 26, -34, 26, 41,
	59, -26, 24, 17, -27, 30, 28, 29, 35, 36,
	37, 33, 31, 34, 32, 38, -48, 15, -48, -48,
	-18, -20, 15, 2, -19, -18, -19, 15, 15, 15,
	-61, 22, 22, -61, 22, -63, 21, 2, 22, 22,
	-61, 22, 7, 2, -43, -61, -31, 19, -31, 26,
	-31, -25, -25, 24, 17, 2, 17, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, -51, -8,
	86, 85, -21, 22, -22, -4, 22, 22, -61, 22,
	7, 21, 2, 22, -4, 22, -31, 26, 26, 17,
	-27, -30, 59, -31, -35, -35, -35, -32, -28, 14,
	-28, -30, -28, -30, -11, 103, 104, 105, 106, 22,
	-51, -48, -48, 22, 7, 2, 4, 7, -61, -31,
	-31, -31, -29, -35, 22, 22, -22, -4, -61, 22,
	24, 21, 2, 22, 21, -35,
}

var yyDef = [...]int16{
	0, -2, 166, 166, 0, 0, 7, 6, 1, 166,
	129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
	139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
	149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
	159, 160, 161, 162, 0, 2, -2, 3, 4, 8,
	9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
	19, 20, 21, 22, 0, 139, 0, 157, 158, 0,
	279, 280, 0, 290, 0, 113, 114, 317, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, 273, 274, 0, 5,
	128, 0, 165, 168, 0, 172, 176, 291, 177, 181,
	48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
	48, 48, 48, 48, 48, 48, 48, 48, 0, 97,
	98, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	25, 26, 0, 0, 0, 83, 84, 85, 0, 86,
	0, 87, 0, 0, 22, 111, -2, 112, 0, 117,
	119, 0, 123, 127, 163, 0, 169, 0, 175, 0,
	180, 0, 47, 56, 52, 53, 49, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 95, 96, 294, 0, 0, 0,
	0, 303, 304, 305, 0, 99, 0, 101, 285, 286,
	102, 103, 281, 282, 0, 0, 0, 110, 94, 306,
	0, 0, 0, 0, 308, 309, 310, 311, 312, 313,
	23, 24, 27, 0, 65, 28, 0, 89, 91, 89,
	89, 22, 93, 318, 115, 0, 120, 0, 126, 275,
	276, 277, 278, 0, 164, 167, 170, 173, 171, 174,
	179, 182, 184, 187, 191, 192, 193, 0, 29, 0,
	0, 0, 0, 0, -2, -2, 30, 31, 32, 33,
	34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
	44, 45, 46, 295, 0, 0, 0, 0, 307, 0,
	0, 0, 0, 0, 283, 284, 104, 0, 109, 0,
	0, 0, 0, 64, 76, 78, 79, 80, 235, 236,
	237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
	247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
	257, 258, 259, 260, 261, 262, 263, 264, 265, 266,
	267, 268, 269, 270, 271, 272, 88, 92, 0, 116,
	118, 121, 125, 122, 124, 0, 0, 0, 0, 0,
	0, 0, 0, 197, 199, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 57, 0, 58, 59,
	50, 51, 0, 69, 54, 293, 55, 0, 0, 0,
	0, 296, 297, 0, 100, 0, 106, 108, 314, 315,
	0, 62, 0, 77, 90, 0, 183, 287, 185, 0,
	188, 0, 0, 0, 195, 200, 196, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 68, 71, 73, 298, 299, 0, 302,
	0, 105, 107, 63, 75, 316, 186, 0, 0, 194,
	198, 201, 0, 289, 202, 203, 204, 205, 206, 0,
	207, 208, 209, 210, 211, 217, 218, 219, 220, 81,
	0, 60, 61, 66, 0, 72, 0, 0, 0, 189,
	190, 288, 0, 215, 82, 67, 70, 74, 0, 300,
	0, 213, 216, 301, 212, 214,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).addParseErrf(posrange.PositionRange{}, "no expression found in input")
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("", "")
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node, false)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node, false)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node, true)
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{}, false)
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			vm := yyVAL.node.(*BinaryExpr).VectorMatching
			vm.On = true
			vm.MatchingLabels = yyDollar[3].on_match.labels
			vm.MatchingLabelMappings = yyDollar[3].on_match.mappings
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			fill := yyDollar[3].node.(*NumberLiteral).Val
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.LHS = &fill
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.RHS = &fill
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			fill := yyDollar[3].node.(*NumberLiteral).Val
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.LHS = &fill
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			fill := yyDollar[3].node.(*NumberLiteral).Val
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.RHS = &fill
		}
	case 60:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
			fill_left := yyDollar[3].node.(*NumberLiteral).Val
			fill_right := yyDollar[5].node.(*NumberLiteral).Val
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.LHS = &fill_left
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.RHS = &fill_right
		}
	case 61:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			fill_right := yyDollar[3].node.(*NumberLiteral).Val
			fill_left := yyDollar[5].node.(*NumberLiteral).Val
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.LHS = &fill_left
			yyVAL.node.(*BinaryExpr).VectorMatching.FillValues.RHS = &fill_right
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.strings = []string{}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.on_match = yyDollar[2].on_match
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.on_match = yyDollar[2].on_match
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.on_match = &onMatchClause{labels: []string{}}
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.on_match = &onMatchClause{}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.on_match = yyDollar[1].on_match
			yyVAL.on_match.add(yyDollar[3].label_map)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.on_match = &onMatchClause{}
			yyVAL.on_match.add(yyDollar[1].label_map)
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.on_match = yyDollar[1].on_match
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.label_map = LabelMapping{Left: yyDollar[1].item.Val, Right: yyDollar[1].item.Val}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.label_map = LabelMapping{Left: yyDollar[1].item.Val, Right: yyDollar[3].item.Val}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !model.UTF8Validation.IsValidLabelName(yyDollar[1].item.Val) {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid label name for grouping: %q", yyDollar[1].item.Val)
			}
			yyVAL.item = yyDollar[1].item
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			unquoted := yylex.(*parser).unquoteString(yyDollar[1].item.Val)
			if !model.UTF8Validation.IsValidLabelName(unquoted) {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid label name for grouping: %q", unquoted)
			}
			yyVAL.item = yyDollar[1].item
			yyVAL.item.Pos++
			yyVAL.item.Val = unquoted
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node.(*NumberLiteral)
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			nl := yyDollar[3].node.(*NumberLiteral)
			if yyDollar[2].item.Typ == SUB {
				nl.Val *= -1
			}
			nl.PosRange.Start = yyDollar[2].item.Pos
			yyVAL.node = nl
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			fn, exist := getFunction(yyDollar[1].item.Val, yylex.(*parser).functions)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			if fn != nil && fn.Experimental && !yylex.(*parser).options.EnableExperimentalFunctions {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "function %q is not enabled", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: posrange.PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			fn, exist := getFunction(yyDollar[1].item.Val, yylex.(*parser).functions)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			if fn != nil && fn.Experimental && !yylex.(*parser).options.EnableExperimentalFunctions {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "function %q is not enabled", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: posrange.PositionRange{
					Start: yyDollar[1].item.PositionRange().Start,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			fn, exist := getFunction(yyDollar[1].item.Val, yylex.(*parser).functions)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			if fn != nil && fn.Experimental && !yylex.(*parser).options.EnableExperimentalFunctions {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "function %q is not enabled", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: posrange.PositionRange{
					Start: yyDollar[1].item.PositionRange().Start,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			fn, exist := getFunction(yyDollar[1].item.Val, yylex.(*parser).functions)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			if fn != nil && fn.Experimental && !yylex.(*parser).options.EnableExperimentalFunctions {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "function %q is not enabled", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: posrange.PositionRange{
					Start: yyDollar[1].item.PositionRange().Start,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			fn, exist := getFunction(yyDollar[1].item.Val, yylex.(*parser).functions)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			if fn != nil && fn.Experimental && !yylex.(*parser).options.EnableExperimentalFunctions {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "function %q is not enabled", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: posrange.PositionRange{
					Start: yyDollar[1].item.PositionRange().Start,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = Expressions{}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if numLit, ok := yyDollar[1].node.(*NumberLiteral); ok {
				if numLit.Val <= 0 {
					yylex.(*parser).addParseErrf(numLit.PositionRange(), "duration must be greater than 0")
					yyVAL.node = &NumberLiteral{Val: 0} // Return 0 on error.
					break
				}
				yyVAL.node = yyDollar[1].node
				break
			}
			yyVAL.node = yyDollar[1].node
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if numLit, ok := yyDollar[3].node.(*NumberLiteral); ok {
				yylex.(*parser).addOffset(yyDollar[1].node, time.Duration(math.Round(numLit.Val*float64(time.Second))))
				yyVAL.node = yyDollar[1].node
				break
			}
			yylex.(*parser).addOffsetExpr(yyDollar[1].node, yyDollar[3].node.(*DurationExpr))
			yyVAL.node = yyDollar[1].node
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("offset", "number, duration, step(), or range()")
			yyVAL.node = yyDollar[1].node
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).setAnchored(yyDollar[1].node)
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).setSmoothed(yyDollar[1].node)
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).setTimestamp(yyDollar[1].node, yyDollar[3].float)
			yyVAL.node = yyDollar[1].node
		}
	case 100:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yylex.(*parser).setAtModifierPreprocessor(yyDollar[1].node, yyDollar[3].item)
			yyVAL.node = yyDollar[1].node
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("@", "timestamp")
			yyVAL.node = yyDollar[1].node
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.OriginalOffset != 0 {
				errMsg = "no offset modifiers allowed before range"
			} else if vs.Timestamp != nil {
				errMsg = "no @ modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, "%s", errMsg)
			}

			var rangeNl time.Duration
			if numLit, ok := yyDollar[3].node.(*NumberLiteral); ok {
				rangeNl = time.Duration(math.Round(numLit.Val * float64(time.Second)))
			}
			rangeExpr, _ := yyDollar[3].node.(*DurationExpr)
			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          rangeNl,
				RangeExpr:      rangeExpr,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 105:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			var rangeNl time.Duration
			var stepNl time.Duration
			if numLit, ok := yyDollar[3].node.(*NumberLiteral); ok {
				rangeNl = time.Duration(math.Round(numLit.Val * float64(time.Second)))
			}
			rangeExpr, _ := yyDollar[3].node.(*DurationExpr)
			if numLit, ok := yyDollar[5].node.(*NumberLiteral); ok {
				stepNl = time.Duration(math.Round(numLit.Val * float64(time.Second)))
			}
			stepExpr, _ := yyDollar[5].node.(*DurationExpr)
			yyVAL.node = &SubqueryExpr{
				Expr:      yyDollar[1].node.(Expr),
				Range:     rangeNl,
				RangeExpr: rangeExpr,
				Step:      stepNl,
				StepExpr:  stepExpr,
				EndPos:    yyDollar[6].item.Pos + 1,
			}
		}
	case 106:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			var rangeNl time.Duration
			if numLit, ok := yyDollar[3].node.(*NumberLiteral); ok {
				rangeNl = time.Duration(math.Round(numLit.Val * float64(time.Second)))
			}
			rangeExpr, _ := yyDollar[3].node.(*DurationExpr)
			yyVAL.node = &SubqueryExpr{
				Expr:      yyDollar[1].node.(Expr),
				Range:     rangeNl,
				RangeExpr: rangeExpr,
				EndPos:    yyDollar[5].item.Pos + 1,
			}
		}
	case 107:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 108:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery selector", "number, duration, step(), range(), or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 109:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("subquery or range selector", "number, duration, step(), or range()")
			yyVAL.node = yyDollar[1].node
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 116:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.matcher = yylex.(*parser).newMetricNameMatcher(yyDollar[1].item)
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			b := labels.NewBuilder(yyDollar[2].labels)
			b.Set(labels.MetricName, yyDollar[1].item.Val)
			yyVAL.labels = b.Labels()
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.labels = labels.New(yyDollar[2].lblList...)
		}
	case 164:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.labels = labels.New(yyDollar[2].lblList...)
		}
	case 165:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.labels = labels.New()
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.labels = labels.New()
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.lblList = append(yyDollar[1].lblList, yyDollar[3].label)
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.lblList = []labels.Label{yyDollar[1].label}
		}
	case 169:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.lblList = yyDollar[1].lblList
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.label = labels.Label{Name: labels.MetricName, Value: yyDollar[1].item.Val}
		}
	case 173:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 175:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 178:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 180:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.series = yyDollar[1].series
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			// Add an additional value for time 0, which we ignore in tests.
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 186:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			// Add an additional value for time 0, which we ignore in tests.
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.series = []SequenceValue{yylex.(*parser).newHistogramSequenceValue(yyDollar[1].histogram)}
		}
	case 188:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.series = []SequenceValue{}
			// Add an additional value for time 0, which we ignore in tests.
			sv := yylex.(*parser).newHistogramSequenceValue(yyDollar[1].histogram)
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, sv)
				//$1 += $2
			}
		}
	case 189:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			val, err := yylex.(*parser).histogramsIncreaseSeries(yyDollar[1].histogram, yyDollar[3].histogram, yyDollar[5].uint)
			if err != nil {
				yylex.(*parser).addSemanticError(err)
			}
			yyVAL.series = val
		}
	case 190:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			val, err := yylex.(*parser).histogramsDecreaseSeries(yyDollar[1].histogram, yyDollar[3].histogram, yyDollar[5].uint)
			if err != nil {
				yylex.(*parser).addSemanticError(err)
			}
			yyVAL.series = val
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 194:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&yyDollar[2].descriptors)
		}
	case 195:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&yyDollar[2].descriptors)
		}
	case 196:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			m := yylex.(*parser).newMap()
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&m)
		}
	case 197:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			m := yylex.(*parser).newMap()
			yyVAL.histogram = yylex.(*parser).buildHistogramFromMap(&m)
		}
	case 198:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = *(yylex.(*parser).mergeMaps(&yyDollar[1].descriptors, &yyDollar[3].descriptors))
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.descriptors = yyDollar[1].descriptors
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*parser).unexpected("histogram description", "histogram description key, e.g. buckets:[5 10 7]")
		}
	case 201:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["schema"] = yyDollar[3].int
		}
	case 202:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["sum"] = yyDollar[3].float
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["count"] = yyDollar[3].float
		}
	case 204:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["z_bucket"] = yyDollar[3].float
		}
	case 205:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["z_bucket_w"] = yyDollar[3].float
		}
	case 206:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["custom_values"] = yyDollar[3].bucket_set
		}
	case 207:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["buckets"] = yyDollar[3].bucket_set
		}
	case 208:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["offset"] = yyDollar[3].int
		}
	case 209:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["n_buckets"] = yyDollar[3].bucket_set
		}
	case 210:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["n_offset"] = yyDollar[3].int
		}
	case 211:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.descriptors = yylex.(*parser).newMap()
			yyVAL.descriptors["counter_reset_hint"] = yyDollar[3].item
		}
	case 212:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.bucket_set = yyDollar[2].bucket_set
		}
	case 213:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bucket_set = yyDollar[2].bucket_set
		}
	case 214:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bucket_set = append(yyDollar[1].bucket_set, yyDollar[3].float)
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bucket_set = []float64{yyDollar[1].float}
		}
	case 279:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 280:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			var err error
			var dur time.Duration
			dur, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
			yyVAL.node = &NumberLiteral{
				Val:      dur.Seconds(),
				PosRange: yyDollar[1].item.PositionRange(),
				Duration: true,
			}
		}
	case 281:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 282:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			var err error
			var dur time.Duration
			dur, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
			yyVAL.float = dur.Seconds()
		}
	case 283:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.float = yyDollar[2].float
		}
	case 284:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 287:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 288:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.int = -int64(yyDollar[2].uint)
		}
	case 289:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.int = int64(yyDollar[1].uint)
		}
	case 290:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 291:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.item = Item{
				Typ: METRIC_IDENTIFIER,
				Pos: yyDollar[1].item.PositionRange().Start,
				Val: yylex.(*parser).unquoteString(yyDollar[1].item.Val),
			}
		}
	case 292:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.strings = nil
		}
	case 294:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			nl := yyDollar[1].node.(*NumberLiteral)
			if durationLiteralOutOfRange(nl.Val) {
				yylex.(*parser).addParseErrf(nl.PosRange, "duration out of range")
				yyVAL.node = &NumberLiteral{Val: 0}
				break
			}
			yyVAL.node = nl
		}
	case 295:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			nl := yyDollar[2].node.(*NumberLiteral)
			if yyDollar[1].item.Typ == SUB {
				nl.Val *= -1
			}
			if durationLiteralOutOfRange(nl.Val) {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "duration out of range")
				yyVAL.node = &NumberLiteral{Val: 0}
				break
			}
			nl.PosRange.Start = yyDollar[1].item.Pos
			yyVAL.node = nl
		}
	case 296:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			de := &DurationExpr{
				Op:       STEP,
				StartPos: yyDollar[1].item.PositionRange().Start,
				EndPos:   yyDollar[3].item.PositionRange().End,
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 297:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			de := &DurationExpr{
				Op:       RANGE,
				StartPos: yyDollar[1].item.PositionRange().Start,
				EndPos:   yyDollar[3].item.PositionRange().End,
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 298:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			de := &DurationExpr{
				Op: yyDollar[1].item.Typ,
				RHS: &DurationExpr{
					Op:       STEP,
					StartPos: yyDollar[2].item.PositionRange().Start,
					EndPos:   yyDollar[4].item.PositionRange().End,
				},
				StartPos: yyDollar[1].item.Pos,
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 299:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			de := &DurationExpr{
				Op: yyDollar[1].item.Typ,
				RHS: &DurationExpr{
					Op:       RANGE,
					StartPos: yyDollar[2].item.PositionRange().Start,
					EndPos:   yyDollar[4].item.PositionRange().End,
				},
				StartPos: yyDollar[1].item.Pos,
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 300:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			de := &DurationExpr{
				Op:       yyDollar[1].item.Typ,
				StartPos: yyDollar[1].item.PositionRange().Start,
				EndPos:   yyDollar[6].item.PositionRange().End,
				LHS:      yyDollar[3].node.(Expr),
				RHS:      yyDollar[5].node.(Expr),
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 301:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			de := &DurationExpr{
				Op:       yyDollar[1].item.Typ,
				StartPos: yyDollar[1].item.Pos,
				EndPos:   yyDollar[6].node.PositionRange().End,
				RHS: &DurationExpr{
					Op:       yyDollar[2].item.Typ,
					StartPos: yyDollar[2].item.PositionRange().Start,
					EndPos:   yyDollar[6].node.PositionRange().End,
					LHS:      yyDollar[4].node.(Expr),
					RHS:      yyDollar[6].node.(Expr),
				},
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 302:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).applyUnaryOpToDurationExpr(yyDollar[1].item, yyDollar[3].node.(Node), true)
		}
	case 306:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			nl := yyDollar[1].node.(*NumberLiteral)
			if durationLiteralOutOfRange(nl.Val) {
				yylex.(*parser).addParseErrf(nl.PosRange, "duration out of range")
				yyVAL.node = &NumberLiteral{Val: 0}
				break
			}
			yyVAL.node = nl
		}
	case 307:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yylex.(*parser).applyUnaryOpToDurationExpr(yyDollar[1].item, yyDollar[2].node.(Node), false)
		}
	case 308:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[1].node.(Expr))
			yyVAL.node = &DurationExpr{Op: ADD, LHS: yyDollar[1].node.(Expr), RHS: yyDollar[3].node.(Expr)}
		}
	case 309:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[1].node.(Expr))
			yyVAL.node = &DurationExpr{Op: SUB, LHS: yyDollar[1].node.(Expr), RHS: yyDollar[3].node.(Expr)}
		}
	case 310:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[1].node.(Expr))
			yyVAL.node = &DurationExpr{Op: MUL, LHS: yyDollar[1].node.(Expr), RHS: yyDollar[3].node.(Expr)}
		}
	case 311:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[1].node.(Expr))
			if nl, ok := yyDollar[3].node.(*NumberLiteral); ok && nl.Val == 0 {
				yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "division by zero")
				yyVAL.node = &NumberLiteral{Val: 0}
				break
			}
			yyVAL.node = &DurationExpr{Op: DIV, LHS: yyDollar[1].node.(Expr), RHS: yyDollar[3].node.(Expr)}
		}
	case 312:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[1].node.(Expr))
			if nl, ok := yyDollar[3].node.(*NumberLiteral); ok && nl.Val == 0 {
				yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "modulo by zero")
				yyVAL.node = &NumberLiteral{Val: 0}
				break
			}
			yyVAL.node = &DurationExpr{Op: MOD, LHS: yyDollar[1].node.(Expr), RHS: yyDollar[3].node.(Expr)}
		}
	case 313:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[1].node.(Expr))
			yyVAL.node = &DurationExpr{Op: POW, LHS: yyDollar[1].node.(Expr), RHS: yyDollar[3].node.(Expr)}
		}
	case 314:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			de := &DurationExpr{
				Op:       STEP,
				StartPos: yyDollar[1].item.PositionRange().Start,
				EndPos:   yyDollar[3].item.PositionRange().End,
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 315:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			de := &DurationExpr{
				Op:       RANGE,
				StartPos: yyDollar[1].item.PositionRange().Start,
				EndPos:   yyDollar[3].item.PositionRange().End,
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 316:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			de := &DurationExpr{
				Op:       yyDollar[1].item.Typ,
				StartPos: yyDollar[1].item.PositionRange().Start,
				EndPos:   yyDollar[6].item.PositionRange().End,
				LHS:      yyDollar[3].node.(Expr),
				RHS:      yyDollar[5].node.(Expr),
			}
			yylex.(*parser).experimentalDurationExpr(de)
			yyVAL.node = de
		}
	case 318:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*parser).experimentalDurationExpr(yyDollar[2].node.(Expr))
			if durationExpr, ok := yyDollar[2].node.(*DurationExpr); ok {
				durationExpr.Wrapped = true
				yyVAL.node = durationExpr
				break
			}
			yyVAL.node = yyDollar[2].node
		}
	}
	goto yystack /* stack new state and value */
}
